apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: aitask-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: vanshsuri07/ai-task-backend:d57be0c
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: aitask-config
            - secretRef:
                name: aitask-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: aitask-namespace
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
