apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: aitask-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: vanshsuri07/ai-task-frontend:d57be0c
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
          envFrom:
            - configMapRef:
                name: aitask-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: aitask-namespace
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
